//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtvaranjePutnihNaloga_Gikić.Models.Baza_zaposlenika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PutniNaloziEntities : DbContext
    {
        public PutniNaloziEntities()
            : base("name=PutniNaloziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Odjel> Odjel { get; set; }
        public virtual DbSet<Zaposlenici> Zaposlenici { get; set; }
        public virtual DbSet<vwZaposleniciPoOdjelima> vwZaposleniciPoOdjelima { get; set; }
        public virtual DbSet<PrijevoznaSredstva> PrijevoznaSredstva { get; set; }
        public virtual DbSet<TipPrijevoznogSredstva> TipPrijevoznogSredstva { get; set; }
        public virtual DbSet<PrivatnoVozilo> PrivatnoVozilo { get; set; }
        public virtual DbSet<Smejstaj> Smejstaj { get; set; }
        public virtual DbSet<PutniNalog> PutniNalog { get; set; }
    }
}
