//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtvaranjePutnihNaloga_Gikić.Models.Baza_zaposlenika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odjel
    {
        public Odjel()
        {
            this.Zaposlenici = new HashSet<Zaposlenici>();
        }
    
        public int ID { get; set; }
        public string Ime_odjela { get; set; }
    
        public virtual ICollection<Zaposlenici> Zaposlenici { get; set; }
    }
}
