//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtvaranjePutnihNaloga_Gikić.Models.Baza_zaposlenika
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


     [MetadataType(typeof(OtvaranjePutnihNaloga_Gikić.Models.MetadataKlasa.MetadataSmjestaj))]
    public partial class Smejstaj
    {
        public int ID { get; set; }
        public System.DateTime Prvo_noćenje { get; set; }
        public System.DateTime Zadnje_noćenje { get; set; }
        public System.DateTime Dolazak_u_smještaj { get; set; }
        public System.DateTime Odlazak_iz_smještaja { get; set; }
        public string Komentar { get; set; }
        public int IDPutnogNaloga { get; set; }
    
        public virtual PutniNalog PutniNalog { get; set; }
    }
}
